// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.bigdataconcept.akka.distributed.iot.smart.grid.proto

object ModelsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto,
    com.google.protobuf.wrappers.WrappersProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.bigdataconcept.akka.distributed.iot.smart.grid.proto.Device,
      com.bigdataconcept.akka.distributed.iot.smart.grid.proto.IoTEvent,
      com.bigdataconcept.akka.distributed.iot.smart.grid.proto.SendIoTDataTelemetry
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgxtb2RlbHMucHJvdG8SOGNvbS5iaWdkYXRhY29uY2VwdC5ha2thLmRpc3RyaWJ1dGVkLmlvdC5zbWFydC5ncmlkLnByb3RvG
  hVzY2FsYXBiL3NjYWxhcGIucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90byKAAgoGRGV2aWNlEikKCGRldmljZ
  UlkGAEgASgJQg3iPwoSCGRldmljZUlkUghkZXZpY2VJZBIyCgtsb25naXRpdHVkZRgCIAEoAUIQ4j8NEgtsb25naXRpdHVkZVILb
  G9uZ2l0aXR1ZGUSLwoKbGF0aXRpdHVkZRgDIAEoAUIP4j8MEgpsYXRpdGl0dWRlUgpsYXRpdGl0dWRlEi8KCmRldmljZVR5cGUYB
  CABKAlCD+I/DBIKZGV2aWNlVHlwZVIKZGV2aWNlVHlwZRI1CgxkZXZpY2VOdW1iZXIYBSABKAlCEeI/DhIMZGV2aWNlTnVtYmVyU
  gxkZXZpY2VOdW1iZXIiuwEKCElvVEV2ZW50EmUKBmRldmljZRgBIAEoCzJALmNvbS5iaWdkYXRhY29uY2VwdC5ha2thLmRpc3Rya
  WJ1dGVkLmlvdC5zbWFydC5ncmlkLnByb3RvLkRldmljZUIL4j8IEgZkZXZpY2VSBmRldmljZRIdCgRkYXRhGAIgASgJQgniPwYSB
  GRhdGFSBGRhdGESKQoIZXZlbnROdW0YAyABKAVCDeI/ChIIZXZlbnROdW1SCGV2ZW50TnVtIqUBChRTZW5kSW9URGF0YVRlbGVtZ
  XRyeRJlCgZkZXZpY2UYASABKAsyQC5jb20uYmlnZGF0YWNvbmNlcHQuYWtrYS5kaXN0cmlidXRlZC5pb3Quc21hcnQuZ3JpZC5wc
  m90by5EZXZpY2VCC+I/CBIGZGV2aWNlUgZkZXZpY2USJgoHaW90RGF0YRgCIAEoCUIM4j8JEgdpb3REYXRhUgdpb3REYXRhYgZwc
  m90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      scalapb.options.ScalapbProto.javaDescriptor,
      com.google.protobuf.wrappers.WrappersProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}